USE [master]
GO

/****** Object:  Database [MijemTest]    Script Date: 19/02/2018 8:42:45 PM ******/
CREATE DATABASE [MijemTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MijemTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MijemTest.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MijemTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MijemTest_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MijemTest] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MijemTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MijemTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MijemTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MijemTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MijemTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MijemTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [MijemTest] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MijemTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MijemTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MijemTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MijemTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MijemTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MijemTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MijemTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MijemTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MijemTest] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MijemTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MijemTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MijemTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MijemTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MijemTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MijemTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MijemTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MijemTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MijemTest] SET  MULTI_USER 
GO

ALTER DATABASE [MijemTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MijemTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MijemTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MijemTest] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MijemTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MijemTest] SET  READ_WRITE 
GO


